version: '3.8'

services:
  backend:
    build: ./todo-backend
    ports:
      - "3000:3000"
    volumes:
      - ./todo-backend:/app
      - /app/node_modules
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: always

